### PR TITLE
Import vuetify directly.

### PR DESCRIPTION
**Pull request by gluons**
Import vuetify directly in `main.js`.

Vuetify stylesheet will be bundled into your build.

### CODE REVIEW

**Comment by exhuma** [comment]
Amazing! I'll give it a try! :cake:

**Comment by exhuma** [comment]
The CSS seems to work now. But, now that I tried clicking around in the UI a bit I realized that the events no longer seem to fire.

For example, [this "Delete" button](https://github.com/exhuma/powonline/blob/vuetify/frontend/powonline/src/components/StationBlock.vue#L13) does no longer work. It whould listen to an "onclick" event and call [deleteStation](https://github.com/exhuma/powonline/blob/vuetify/frontend/powonline/src/components/StationBlock.vue#L28). But I don't see anything in the logs anymore, and the related remote XHR call does not seem to happen.

Any ideas what that could be? Do I have to register the event handler differently? Does the normal `@click` argument no longer work with vuetify? I also tried the `v-on:click`  without luck.

**Comment by gluons** [comment]
@exhuma Try [`@click.native`](https://vuejs.org/v2/guide/components.html#Binding-Native-Events-to-Components). It probably works.

**Comment by exhuma** [comment]
Yes! This works indeed. Thanks a lot. I've looked at the link to the docs and I'm not sure I understand correctly. What exactly is happening here with the `.native` modifier? I'm guessing that this would be an event native to the browser? If that's the case, what is the "normal" `click` event in vuejs? Is that an abstraction around browser differences? If so, won't I run into trouble down the road by using `.native`?

The application is for a very limited audience (less than 20 people) so I can run it in a very controlled environment and browser differences should not pose an issue.

But I'd still like to understand in more detail.

I have not done JS in *ages*, but I'm more than willing to read up on this topic. Should I look for this in the MDN reference? Or is this rather related to vuejs itself? I'm not quite sure where to start searching.

**Comment by gluons** [comment]
`.native` modifier will attach the event directly on the root element of a component.

If you didn't use `.native` modifier, it will attach [the custom event](https://vuejs.org/v2/guide/components.html#Custom-Events) on a component.
> the custom event will be raised by `$emit` method.

**Comment by exhuma** [comment]
Ah... I understand. Thanks a lot for taking the time to explain :) Much appreciated!

**Pull request merged**
